### ISSUE TITLE
403 when script tries to download zip

### ISSUE THREAD

**Issue by savelichalex** [yannbolliger/notion-exporter#3]
It looks like notion looks for a `file_token` cookie now, but I have no idea, how to get this token, without putting the url for a zip file in browser and look for cookies it sets

**Comment by yannbolliger** [comment]
I'm unfortunately experiencing the same problem. Will hopefully have time to look into it soon. Otherwise, contributions are very welcome 😉

**Comment by yannbolliger** [comment]
Update
The next release temporarily fixes the problem by forcing you to also provide a `file_token`.
