### ISSUE TITLE
Missing Fields in CSV Export from Database

### ISSUE THREAD

**Issue by danvoronov** [yannbolliger/notion-exporter#4]
Hello,

I hope this message finds you well. I've encountered an issue with the CSV export feature in the Notion Exporter tool. Previously, when exporting data from a database, all fields were included in the CSV file. However, it seems that now only the fields from the first tab are being exported, and some fields may be missing.

I noticed that in Notion itself, a new option has been added to control which fields are included in the export. However, this option is not available in your Notion Exporter library.

![image](https://github.com/yannbolliger/notion-exporter/assets/3093815/b36e6034-dcee-499a-b8d5-48921eb0867a)

This issue is affecting my workflow as I rely on having access to all the data fields in the exported CSV file. It would be greatly appreciated if this issue could be addressed and resolved in an upcoming update of the Notion Exporter tool.

If you need any additional information or would like me to provide more details about this problem, please let me know. I'm eager to assist in any way I can to help resolve this issue.

**Comment by danvoronov** [comment]
plz change
```
  getCsvString = (idOrUrl: string, spaceId: string): Promise<string> =>
    this.getFileString(idOrUrl, spaceId, (e) => e.name.endsWith(".csv"))

```
to
```
  getCsvString = (idOrUrl: string, spaceId: string): Promise<string> =>
    this.getFileString(idOrUrl, spaceId, (e) => e.name.endsWith("_all.csv"))

```

**Comment by yannbolliger** [comment]
Coming back to this now. I'll look into your proposed change but will also contemplate some flags to adapt the behaviour.

**Comment by yannbolliger** [comment]
Fixed with upcoming release.
